In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from linearregression import * # Import my implemtation of Linear Regression
sns.set_theme()

 Let us generate data using  this
linear function for our model test, our model will try to estimate the weights and bias term
of this function, this function has 3 features so our weights will be 3 plus 1 bias term. Our function is truly linear, however it should be noted that in real world application you can hardly see any relationship that is wholely linear. But we will simulate data using this function, our function says: "I will generate dataset using some coefficients and intercept, please find those coefficients and intercept that I used to generate the dataset." So the coefficients are [7, 2, -5] and the intercept is 3. Our model will attempt to find these four values.

In [2]:
f = lambda x1, x2, x3: 7*x1 + 2*x2 - 5*x3 + 3

In [3]:
#Generate the training data using our function
np.random.seed(42)
X = np.random.randint(1, 100, size=(1_000, 3))
Y = f(X[:,0], X[:,1], X[:,2])
Y = Y[:, np.newaxis]
print(X[:5])
print(Y[:5])

[[52 93 15]
 [72 61 21]
 [83 87 75]
 [75 88 24]
 [ 3 22 53]]
[[ 478]
 [ 524]
 [ 383]
 [ 584]
 [-197]]


In [4]:
X.shape

(1000, 3)

In [5]:
Y.shape

(1000, 1)

In [6]:
#Generate test data using our function
X_test = np.random.randint(1, 10, size=(50, 3))
Y_true = f(X_test[:,0], X_test[:,1], X_test[:,2])
Y_true = Y_true[:, np.newaxis]

In [7]:
X_test.shape

(50, 3)

In [8]:
Y_true.shape

(50, 1)

In [9]:
W = np.random.randn(X.shape[1], 1) * np.sqrt(2/X.shape[1])
b = 0.0

In [10]:
print(W)

[[-0.51315574]
 [ 0.49192058]
 [-0.5789236 ]]


In [11]:
linear_regression = LinearRegression()

In [ ]:
model = linear_regression.fit(X, Y, W, b,X_test,Y_true,
    optimizer='adam',learning_rate=0.001, epochs=1, batch_size=1, num_iters=100000, bias=True)
W = model['W']
b = model['b']
costs = model['costs']
W_history = model['W_history']
b_history = model['W_history']
iterations = model['iterations']

Running epoch 1 / 1
Running mini-batch 1 / 1
Iteration    0: Cost 11045355.83264394   
Iteration 10000: Cost 21007356.93399203   
Iteration 20000: Cost 21004524.68009415   
Iteration 30000: Cost 20588416.44969027   
Iteration 40000: Cost 10050946.90415854   
Iteration 50000: Cost 1375988.55920513   
Iteration 60000: Cost 3818.82976737   
Iteration 70000: Cost 0.06952205   
Iteration 80000: Cost 0.04187866   
Iteration 90000: Cost 0.04235841   
Iteration 99999: Cost 0.04238827   
Train RMSE: 9270.508725167385
Test RMSE: 169.79801384765514


KeyError: 'W_histories'

Let us view the weights (coefficients) that our model predicted, we can see that it has nearly accurately computed the weights and
bias (intercept).

In [ ]:
W

In [ ]:
b

In [ ]:
predictions = linear_regression.predict(X_test, W, b)

In [ ]:
plt.scatter(Y_true, predictions);

In [ ]:
W_history = np.array(W_history)
W_history.shape

In [ ]:
costs = np.array(costs)
costs.shape

In [ ]:
b_history = np.array(b_history)
b_history.shape

In [ ]:
iterations = np.array(iterations)
iterations

In [ ]:
plt.plot(iterations, costs)
plt.title('The plot of cost against the iterations')
plt.xlabel('iterations')
plt.ylabel('Cost')
plt.show();